version: "3"

services:
  user_cp:
    container_name: user_cp
    build: .
    restart: always
    ports:
    - 8080:8080
    environment:
    - USERS_DB_PASSWORD
    - USERS_DB_DNS
    - USERS_DB_USER
    - USERS_DB_NAME
    depends_on:
    - users_db

  users_db:
    container_name: users_db
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
    - POSTGRES_USER=${USERS_DB_USER}
    - POSTGRES_PORT=5432
    - POSTGRES_DB=${USERS_DB_NAME}
